### ISSUE TITLE
flacfan.com is down!

### ISSUE THREAD

**Issue by atmosfar** [flacfan/JFLACTool#1]
Hey, was looking for your EAC guide but it seems like your hosting/DNS is out of action. Is there a backup somewhere?

Thanks!

**Comment by flacfan** [comment]
I stopped hosting the site a while back but you just helped me realize that I can put the guides here on GitHub. Thanks!

I've put them here: [https://github.com/flacfan/EAC-Guides](https://github.com/flacfan/EAC-Guides).

Also I've setup [flacfan.com](http://flacfan.com) to redirect to that repository.
